const assert = require('assert') //(standard node lib) used for making assertion about test
const ganache = require('ganache-cli') // module to help create our local test network for testing
const Web3 = require('web3') // constructor function
const web3 = new Web3(ganache.provider()) //this line of code create new instance of web3 and the provider it accepts allows it to connect to the local test network created by ganache
const { interface, bytecode } = require('../compile') //get ABI and contract bytecod to deploy contract

//initialzing global variables
let accounts
let inbox
const INITIAL_STRING = 'Test initial message'

beforeEach(async () => {
	//Get a list of all unlocked accounts generated by ganache
	accounts = await web3.eth.getAccounts()

	//use one of those accounts to deploy the contract
	inbox = await new web3.eth.Contract(JSON.parse(interface)) // tell web3 what method/structure the inbox contract has
		.deploy({ data: bytecode, arguments: [INITIAL_STRING] }) // tell web3 we want to deploy a new contract
		.send({ from: accounts[0], gas: '1000000' }) // instructs web3 to send out a transaction that creates this contract
})

describe('Inbox', () => {
	it('deploys a contract', () => {
		assert.ok(inbox.options.address)
	})

	it('has a default message', async () => {
		const message = await inbox.methods.message().call()
		assert.equal(message, INITIAL_STRING)
	})

	it('can change the message', async () => {
		await inbox.methods.setMessage('GM!').send({ from: accounts[0] })
		const message = await inbox.methods.message().call()
		assert.equal(message, 'GM!')
	})
})

// simple mocha logic
// class Car {
// 	park() {
// 		return 'stopped'
// 	}

// 	drive() {
// 		return 'vroom'
// 	}
// }

// let car

// beforeEach(() => {
// 	car = new Car()
// })

// describe('Motor', () => {
// 	it('Test park function', () => {
// 		assert.equal(car.park(), 'stopped')
// 	})

// 	it('can drive', () => {
// 		assert.equal(car.drive(), 'vroom')
// 	})
// })
